# -*- coding: utf-8 -*-
"""Build src/data/targetAllocation.generated.js (const TARGET_ALLOCATION).

Reads data/study-plan/target-allocation.json and the PE chapter taxonomy in
dashboard-data.js; fails on unknown chapter ids or any PE QID without a tier.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "study-plan" / "target-allocation.json"
DASHBOARD = ROOT / "dashboard-data.js"
OUTPUT = ROOT / "src" / "data" / "targetAllocation.generated.js"
EXPECTED_QIDS = 323
ROLES = {"high", "combined", "basic"}


def load_taxonomy():
    text = DASHBOARD.read_text(encoding="utf-8")
    start = text.index("const QUESTION_TAXONOMY_MAP")
    begin = text.index("{", start)
    end = text.index("\n};", start)
    return json.loads(text[begin:end + 2])


def build():
    cfg = json.loads(SOURCE.read_text(encoding="utf-8"))
    taxonomy = load_taxonomy()
    chapters_by_subject = {}
    qid_chapter = {}
    for qid, info in taxonomy.items():
        if not qid.startswith("EE-"):
            continue
        sid = qid.split("-")[2]
        chapters_by_subject.setdefault(sid, set()).add(info["primaryChapter"])
        qid_chapter[qid] = (sid, info["primaryChapter"])
    subjects = {}
    tiers = {}
    chapter_tiers = {}
    for sid, subj in cfg["subjects"].items():
        if subj["role"] not in ROLES:
            raise SystemExit(f"bad role for {sid}")
        known = chapters_by_subject.get(sid, set())
        main_ids = [c["id"] for c in subj["mainChapters"]]
        unknown = [c for c in main_ids if c not in known]
        if unknown:
            raise SystemExit(f"subject {sid}: unknown chapter ids {unknown}")
        shared = [c["id"] for c in subj["mainChapters"] if c.get("shared")]
        basic_ids = sorted(known - set(main_ids))
        subjects[sid] = {
            "name": subj["name"], "role": subj["role"], "target": subj["target"],
            "mainChapters": main_ids, "sharedChapters": shared, "basicChapters": basic_ids,
        }
        for c in main_ids:
            chapter_tiers[c] = {"subject": sid, "tier": "main", "shared": c in shared}
        for c in basic_ids:
            chapter_tiers[c] = {"subject": sid, "tier": "basic", "shared": False}
    if sum(s["target"] for s in subjects.values()) != cfg["totalTarget"]:
        raise SystemExit("subject targets do not sum to totalTarget")
    for qid, (sid, chapter) in qid_chapter.items():
        tier = chapter_tiers.get(chapter)
        if not tier or tier["subject"] != sid:
            raise SystemExit(f"{qid}: no tier for chapter {chapter}")
        tiers[qid] = {"tier": tier["tier"], "subject": sid, "chapter": chapter, "shared": tier["shared"]}
    for qid, tier in cfg.get("questionOverrides", {}).items():
        if qid not in tiers:
            raise SystemExit(f"override for unknown QID {qid}")
        if tier not in ("main", "basic"):
            raise SystemExit(f"override {qid}: invalid tier {tier!r}")
        tiers[qid]["tier"] = tier
        tiers[qid]["override"] = True
    if len(tiers) != EXPECTED_QIDS:
        raise SystemExit(f"expected {EXPECTED_QIDS} tiered QIDs, got {len(tiers)}")
    return {
        "totalTarget": cfg["totalTarget"], "passLine": cfg["passLine"],
        "subjects": subjects, "chapterTiers": chapter_tiers,
        "questionTiers": dict(sorted(tiers.items())),
    }


def render_js(data):
    return ("// Generated by scripts/build_target_allocation.py. Do not edit.\n"
            "// Source: data/study-plan/target-allocation.json + QUESTION_TAXONOMY_MAP.\n"
            "const TARGET_ALLOCATION = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n")


def main():
    data = build()
    OUTPUT.write_text(render_js(data), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(data['questionTiers'])} QIDs)")


if __name__ == "__main__":
    sys.exit(main())
