# -*- coding: utf-8 -*-
"""Build per-question hints for the four-stage recall reveal.

Stage ② (起手式) uses the first scoring move from the 起手式急救卡 where a
card exists; stage ③ (陷阱) uses the question's own 「## 失分點」 bullets from
its canonical note.  Questions without either keep the chapter template in
src/state/recallStore.js.

Writes src/data/recallHints.generated.js (const RECALL_HINTS).
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL_GLOB = "📝 個人題解與錯題本/0*/canonical/EE-*.md"
RESCUE_CARDS = ROOT / "docs" / "上榜起手式急救卡_114-108.md"
OUTPUT = ROOT / "src" / "data" / "recallHints.generated.js"

SECTION_RE = r"^## {name}\s*$(.*?)(?=^## |\Z)"
CARD_RE = re.compile(r"^### `(EE-\d{3}-\d{2}-\d+)`.*?$(.*?)(?=^### |^## |\Z)", re.M | re.S)
FIRST_MOVE_RE = re.compile(r"第一個[^：\n]{2,8}：")  # 可得分動作／部分分結構


def section(text, name):
    match = re.search(SECTION_RE.format(name=re.escape(name)), text, re.M | re.S)
    return match.group(1).strip() if match else ""


def traps_from_note(text):
    body = section(text, "失分點")
    bullets = [line for line in body.splitlines() if line.startswith("- ")]
    return "\n".join(bullets)


def activations_from_cards(text):
    cards = {}
    for qid, body in CARD_RE.findall(text):
        found = FIRST_MOVE_RE.search(body)
        if not found:
            raise SystemExit(f"{qid}: rescue card has no 「第一個…：」 first move")
        move = body[found.end():]
        move = re.split(r"^\[完整題解核對\]", move, flags=re.M)[0].strip()
        cards[qid] = move
    return cards


def build():
    hints = {}
    for path in sorted(ROOT.glob(CANONICAL_GLOB)):
        traps = traps_from_note(path.read_text(encoding="utf-8"))
        if traps:
            hints.setdefault(path.stem, {})["trapsMd"] = traps
    for qid, move in activations_from_cards(RESCUE_CARDS.read_text(encoding="utf-8")).items():
        if not any(ROOT.glob(f"📝 個人題解與錯題本/0*/canonical/{qid}.md")):
            raise SystemExit(f"{qid}: rescue card has no canonical note")
        hints.setdefault(qid, {})["activationMd"] = move
    return dict(sorted(hints.items()))


def render_js(hints):
    payload = json.dumps(hints, ensure_ascii=False, indent=1)
    return (
        "// AUTO-GENERATED by scripts/build_recall_hints.py — do not edit.\n"
        "// Per-question hints for the four-stage recall reveal: activationMd from\n"
        "// docs/上榜起手式急救卡_114-108.md, trapsMd from each note's 「## 失分點」.\n"
        f"const RECALL_HINTS = {payload};\n"
    )


def main():
    hints = build()
    OUTPUT.write_text(render_js(hints), encoding="utf-8")
    traps = sum(1 for h in hints.values() if "trapsMd" in h)
    moves = sum(1 for h in hints.values() if "activationMd" in h)
    print(f"wrote {OUTPUT.relative_to(ROOT)}: traps {traps}, activations {moves}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
